# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://dannashen.github.io
date_format: "ordinal"
title: Danna的博客
subtitle: "代码改变人生"
description: "Danna的个人博客"
keywords: Blog, Java
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 10

# ---------------- #
#      Author      #
# ---------------- #
author: DannaShen
organization: 
organization_url: 
github_username: DannaShen
location: BaoDing, China
email: shenlongdan@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: DannaShen/DannaShen.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: DannaShen
    repo: DannaShen.github.io
    oauth:
        client_id: ef818097cb6a0e962f62
        client_secret: 70d67f55d59a82439cd1d0bd8a26d648ca17bd93
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: DannaShen
    repo: DannaShen.github.io
    clientID: 74df77db3ff52097e787
    clientSecret: e4e8f8a29bee05c84643eb9b58e64a3fbb0756d8
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false
#这里都是配置 需要自己申请以后弄
# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
